### PR TITLE
Update and rename #TEMPLATE.md to <KushagraArora300>.md

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by sahanihit** [comment]
some file is conflicting.

**Comment by ghost** [comment]
Hey Nihit i hope you are doing great!!
should i resubmit my request!!

**Comment by sahanihit** [comment]
Please fork the repo do the needful and submit the PR again.
I'll close this one for your and my convenience.

**Comment by ghost** [comment]
Does it mean that this request will not be counted??

**Comment by sahanihit** [comment]
Take a chill pill.. just remove the conflicting file and request the PR again.
I am not going to close it or mark it as invalid.

**Comment by ghost** [comment]
Thanks brother!!
I have 40 minutes left for my previous pr request to mature!! Will it be
matured now or the new request will take more 14 days to mature??

**Comment by sahanihit** [comment]
Don't make a PR now wait for 40 mins if the PR gets accepted then don't
make another PR.
I'll leave the PR as it is.

**Comment by sahanihit** [comment]
2.HTML/#TEMPLATE.html this particular file has the issue

**Comment by ghost** [comment]
Alright!! I will wait and let you know!! It's just 12 minutes more to go!!

**Comment by sahanihit** [comment]
is this PR go accepted or should I close this one?

**Review by anshulhub — APPROVED** [review]

**Review by anshulhub — COMMENTED** [review]
problem in files

**Pull request closed without merging**
